require:
  - "ts-node/register"

extension:
  - "ts"

reqursive: true

reporter: "mocha-junit-reporter"

node-option: [
  "experimental-specifier-resolution=node",
  "loader=ts-node/esm",
  "no-warnings"
]
